- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - common
    - container_runtime

- name: Initialize Kubernetes master
  hosts: master
  become: true
  roles:
    - k8s_master

- name: Join Kubernetes workers
  hosts: workers
  become: true
  roles:
    - k8s_worker
